#pragma once

// ═══════════════════════════════════════════════════════════
// Lane Graph — Phase 3.2: Lane-Level Connectivity at Junctions
// ═══════════════════════════════════════════════════════════
//
// @file lane_graph.hpp
// @brief Lane-to-lane connectivity graph at junctions.
//
// @section Architecture
//
//   road_graph.hpp     = Road network topology (nodes + edges)
//   lane_network.hpp   = Per-road lane representation
//   lane_graph.hpp     = Lane connectivity at junctions (THIS FILE)
//   junction_builder.hpp = Junction geometry from lane links
//
// @section Responsibility
// LaneGraph captures which incoming lanes connect to which outgoing
// lanes at a junction. It is consumed by:
//   - Junction geometry generation (junction_builder.hpp)
//   - Traffic simulation (AI route planning)
//   - OpenDRIVE junction export (lane-to-lane connections)
//   - Visualization (lane connection overlays)
//
// @section Node Detection
// For each road meeting at a junction, we extract lane endpoints:
//   - Incoming: lanes arriving at the junction (heading toward center)
//   - Outgoing: lanes departing from the junction (heading away)
//
// @section Link Generation
// Links are generated by matching incoming to outgoing lanes:
//   - Straight: same lane ID on the opposite road
//   - Left turn: leftmost incoming → rightmost outgoing on left road
//   - Right turn: rightmost incoming → leftmost outgoing on right road
//   - U-turn: same road, opposite direction
//
// @section API Freeze
// NOT YET FROZEN. Will be frozen at Phase 3 Complete.

#include "geometry.hpp"
#include "lane_network.hpp"
#include "road_graph.hpp"
#include <algorithm>
#include <cmath>
#include <string>
#include <vector>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

namespace geo {

// ═══════════════════════════════════════════════════════════
// LaneEndpointType — Incoming or Outgoing
// ═══════════════════════════════════════════════════════════

enum class LaneEndpointType {
    Incoming,   // lane arrives at junction (heading toward center)
    Outgoing    // lane departs from junction (heading away from center)
};

// ═══════════════════════════════════════════════════════════
// LaneNode — A lane endpoint at a junction
// ═══════════════════════════════════════════════════════════
//
// Represents a single lane's connection point at a junction.
// Each road approaching a junction contributes one LaneNode per lane.
//
struct LaneNode {
    std::string id;                     // e.g. "roadA_lane+1_in"
    std::string roadId;                 // parent road
    int laneId = 0;                     // 0=center, negative=left, positive=right
    LaneEndpointType type = LaneEndpointType::Incoming;
    Point2D position;                   // where lane meets junction boundary
    double heading = 0.0;               // direction of travel (radians)
    double width = 3.5;                 // lane width at this point

    // ─── Queries ───

    bool isIncoming() const { return type == LaneEndpointType::Incoming; }
    bool isOutgoing() const { return type == LaneEndpointType::Outgoing; }

    std::string typeName() const {
        return isIncoming() ? "Incoming" : "Outgoing";
    }

    // Human-readable lane label
    std::string laneLabel() const {
        if (laneId == 0) return "Center";
        if (laneId > 0)  return "R+" + std::to_string(laneId);
        return "L" + std::to_string(laneId);
    }
};

// ═══════════════════════════════════════════════════════════
// ManeuverType — Turn type for a lane link
// ═══════════════════════════════════════════════════════════

enum class ManeuverType {
    Straight,
    LeftTurn,
    RightTurn,
    UTurn,
    Merge,
    Diverge
};

// ═══════════════════════════════════════════════════════════
// LaneLink — Connection between incoming and outgoing lanes
// ═══════════════════════════════════════════════════════════
//
// Represents a drivable path from one lane to another through a junction.
// The path is a smooth curve (cubic bezier) connecting the two lane endpoints.
//
struct LaneLink {
    std::string id;                     // e.g. "link_0"
    std::string fromLaneNodeId;         // incoming LaneNode id
    std::string toLaneNodeId;           // outgoing LaneNode id
    ManeuverType maneuver = ManeuverType::Straight;
    std::vector<Point2D> path;          // sampled driving path through junction
    double length = 0.0;                // path length in meters
    std::vector<Point2D> conflictPoints; // where this path crosses others

    // ─── Queries ───

    std::string maneuverName() const {
        switch (maneuver) {
            case ManeuverType::Straight:   return "Straight";
            case ManeuverType::LeftTurn:   return "LeftTurn";
            case ManeuverType::RightTurn:  return "RightTurn";
            case ManeuverType::UTurn:      return "UTurn";
            case ManeuverType::Merge:      return "Merge";
            case ManeuverType::Diverge:    return "Diverge";
        }
        return "Unknown";
    }
};

// ═══════════════════════════════════════════════════════════
// LaneGraph — Full lane connectivity at a single junction
// ═══════════════════════════════════════════════════════════
//
// Contains all lane nodes and links for one junction.
// Built from a RoadGraph junction node and the LaneNetworks of connected roads.
//
struct LaneGraph {
    std::string junctionId;             // RoadNode id this graph belongs to
    std::vector<LaneNode> nodes;
    std::vector<LaneLink> links;

    // ─── Queries ───

    int numNodes() const { return static_cast<int>(nodes.size()); }
    int numLinks() const { return static_cast<int>(links.size()); }

    // All incoming lane nodes
    std::vector<const LaneNode*> incomingNodes() const {
        std::vector<const LaneNode*> result;
        for (const auto& n : nodes)
            if (n.isIncoming()) result.push_back(&n);
        return result;
    }

    // All outgoing lane nodes
    std::vector<const LaneNode*> outgoingNodes() const {
        std::vector<const LaneNode*> result;
        for (const auto& n : nodes)
            if (n.isOutgoing()) result.push_back(&n);
        return result;
    }

    // All links originating from a given lane node
    std::vector<const LaneLink*> linksFrom(const std::string& nodeId) const {
        std::vector<const LaneLink*> result;
        for (const auto& l : links)
            if (l.fromLaneNodeId == nodeId) result.push_back(&l);
        return result;
    }

    // All links arriving at a given lane node
    std::vector<const LaneLink*> linksTo(const std::string& nodeId) const {
        std::vector<const LaneLink*> result;
        for (const auto& l : links)
            if (l.toLaneNodeId == nodeId) result.push_back(&l);
        return result;
    }

    // Find a node by id
    const LaneNode* findNode(const std::string& nodeId) const {
        for (const auto& n : nodes)
            if (n.id == nodeId) return &n;
        return nullptr;
    }
};

// ═══════════════════════════════════════════════════════════
// LaneGraphBuilder — Builds a LaneGraph from road + lane data
// ═══════════════════════════════════════════════════════════

struct LaneGraphBuilder {
    // Tolerance for position matching (meters)
    static constexpr double POSITION_TOLERANCE = 2.0;

    // ─── Build a LaneGraph for a single junction ───
    //
    // @param junction   The RoadNode (must be Junction type)
    // @param graph      The RoadGraph (for edge info)
    // @param laneNets   Map: roadId → LaneNetwork for each connected road
    // @return           LaneGraph with nodes and links
    //
    static LaneGraph build(const RoadNode& junction,
                           const RoadGraph& graph,
                           const std::map<std::string, LaneNetwork>& laneNets) {
        LaneGraph result;
        result.junctionId = junction.id;

        if (!junction.isJunction()) return result;

        // Step 1: Create LaneNodes for each connected road
        for (const auto& roadId : junction.connectedRoadIds) {
            auto it = laneNets.find(roadId);
            if (it == laneNets.end()) continue;
            const auto& net = it->second;

            // Find the edge for this road to determine direction
            const RoadEdge* edge = nullptr;
            for (const auto& e : graph.edges) {
                if (e.roadId == roadId) { edge = &e; break; }
            }
            if (!edge) continue;

            // Determine if this road enters or exits the junction
            // If junction is the 'to' node, road arrives → Incoming lanes
            // If junction is the 'from' node, road departs → Outgoing lanes
            const bool arrivesAtJunction = (edge->toNodeId == junction.id);

            // Get lane centerlines and extract endpoints near the junction
            for (const auto& cl : net.centerlines) {
                if (cl.samples.empty()) continue;

                // Use the endpoint closest to the junction
                const auto& firstPt = cl.samples.front();
                const auto& lastPt  = cl.samples.back();
                double dFirst = dist(firstPt.position, junction.position);
                double dLast  = dist(lastPt.position,  junction.position);
                const auto& endpoint = (dFirst < dLast) ? firstPt : lastPt;

                // Skip if too far from junction
                if (std::min(dFirst, dLast) > 50.0) continue;

                LaneNode node;
                node.roadId = roadId;
                node.laneId = cl.laneId;
                node.position = endpoint.position;
                node.heading = endpoint.heading;
                node.width = 3.5; // default

                // Lane direction:
                // If road arrives at junction: right lanes (id>0) are Incoming,
                //   left lanes (id<0) are Outgoing (opposing traffic)
                // If road departs from junction: right lanes are Outgoing,
                //   left lanes are Incoming
                if (arrivesAtJunction) {
                    node.type = (cl.laneId >= 0) ? LaneEndpointType::Incoming
                                                 : LaneEndpointType::Outgoing;
                } else {
                    node.type = (cl.laneId >= 0) ? LaneEndpointType::Outgoing
                                                 : LaneEndpointType::Incoming;
                }

                // Generate unique id
                node.id = roadId + "_lane" +
                          (cl.laneId >= 0 ? "+" : "") + std::to_string(cl.laneId) +
                          "_" + node.typeName();

                result.nodes.push_back(std::move(node));
            }
        }

        // Step 2: Generate LaneLinks
        auto incoming = result.incomingNodes();
        auto outgoing = result.outgoingNodes();

        int linkIdx = 0;
        for (const auto* in : incoming) {
            for (const auto* out : outgoing) {
                // Don't connect to same road (unless U-turn)
                if (in->roadId == out->roadId) {
                    // U-turn: same road, check if opposite direction
                    // Only allow if no other outgoing on same road
                    bool hasOtherOutgoing = false;
                    for (const auto& o : result.nodes) {
                        if (o.isOutgoing() && o.roadId == in->roadId && o.id != out->id) {
                            hasOtherOutgoing = true;
                            break;
                        }
                    }
                    if (hasOtherOutgoing) continue;

                    // U-turn link
                    LaneLink link;
                    link.id = "link_" + std::to_string(linkIdx++);
                    link.fromLaneNodeId = in->id;
                    link.toLaneNodeId = out->id;
                    link.maneuver = ManeuverType::UTurn;
                    link.path = buildBezierPath(in->position, in->heading,
                                                out->position, out->heading);
                    link.length = pathLength(link.path);
                    result.links.push_back(std::move(link));
                    continue;
                }

                // Determine maneuver type based on angle
                double angle = angleBetween(in->heading, out->heading);

                LaneLink link;
                link.id = "link_" + std::to_string(linkIdx++);
                link.fromLaneNodeId = in->id;
                link.toLaneNodeId = out->id;

                // Classify maneuver by turn angle
                // angle ≈ 0 → Straight, angle ≈ ±90 → Left/Right, ≈ 180 → UTurn
                if (angle < 30.0 * M_PI / 180.0) {
                    link.maneuver = ManeuverType::Straight;
                } else if (angle < 150.0 * M_PI / 180.0) {
                    // Determine left vs right by cross product
                    double dx = out->position.x - in->position.x;
                    double dy = out->position.y - in->position.y;
                    double cross = std::cos(in->heading) * dy - std::sin(in->heading) * dx;
                    link.maneuver = (cross > 0) ? ManeuverType::LeftTurn
                                                : ManeuverType::RightTurn;
                } else {
                    link.maneuver = ManeuverType::UTurn;
                }

                link.path = buildBezierPath(in->position, in->heading,
                                            out->position, out->heading);
                link.length = pathLength(link.path);
                result.links.push_back(std::move(link));
            }
        }

        return result;
    }

private:
    // ─── Geometry helpers ───

    static double dist(const Point2D& a, const Point2D& b) {
        double dx = a.x - b.x, dy = a.y - b.y;
        return std::sqrt(dx * dx + dy * dy);
    }

    static double angleBetween(double h1, double h2) {
        double diff = std::abs(h2 - h1);
        while (diff > 2 * M_PI) diff -= 2 * M_PI;
        if (diff > M_PI) diff = 2 * M_PI - diff;
        return diff;
    }

    static double pathLength(const std::vector<Point2D>& path) {
        double len = 0;
        for (size_t i = 1; i < path.size(); i++) {
            double dx = path[i].x - path[i-1].x;
            double dy = path[i].y - path[i-1].y;
            len += std::sqrt(dx * dx + dy * dy);
        }
        return len;
    }

    // Build a smooth cubic bezier path between two points with headings
    static std::vector<Point2D> buildBezierPath(const Point2D& p0, double h0,
                                                const Point2D& p1, double h1) {
        // Control point distance proportional to the distance between points
        double d = dist(p0, p1);
        double cpDist = std::max(d * 0.4, 3.0);

        // Control points along the heading directions
        Point2D c0{ p0.x + std::cos(h0) * cpDist, p0.y + std::sin(h0) * cpDist };
        Point2D c1{ p1.x - std::cos(h1) * cpDist, p1.y - std::sin(h1) * cpDist };

        // Sample the cubic bezier
        std::vector<Point2D> path;
        int numSamples = 24;
        for (int i = 0; i <= numSamples; i++) {
            double t = static_cast<double>(i) / numSamples;
            double u = 1.0 - t;
            double x = u*u*u * p0.x + 3*u*u*t * c0.x + 3*u*t*t * c1.x + t*t*t * p1.x;
            double y = u*u*u * p0.y + 3*u*u*t * c0.y + 3*u*t*t * c1.y + t*t*t * p1.y;
            path.push_back({x, y});
        }
        return path;
    }
};

} // namespace geo

// ═══════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════

#ifdef DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"
#include "road_v2.hpp"
#include "road_adapter.hpp"

TEST_SUITE("LaneGraph") {

    TEST_CASE("LaneNode defaults") {
        geo::LaneNode node;
        CHECK(node.id == "");
        CHECK(node.roadId == "");
        CHECK(node.laneId == 0);
        CHECK(node.type == geo::LaneEndpointType::Incoming);
        CHECK(node.isIncoming());
        CHECK_FALSE(node.isOutgoing());
        CHECK(node.typeName() == "Incoming");
        CHECK(node.laneLabel() == "Center");
    }

    TEST_CASE("LaneNode lane labels") {
        geo::LaneNode node;
        node.laneId = 2;
        CHECK(node.laneLabel() == "R+2");
        node.laneId = -3;
        CHECK(node.laneLabel() == "L-3");
    }

    TEST_CASE("LaneLink maneuver names") {
        geo::LaneLink link;
        link.maneuver = geo::ManeuverType::Straight;
        CHECK(link.maneuverName() == "Straight");
        link.maneuver = geo::ManeuverType::LeftTurn;
        CHECK(link.maneuverName() == "LeftTurn");
        link.maneuver = geo::ManeuverType::RightTurn;
        CHECK(link.maneuverName() == "RightTurn");
        link.maneuver = geo::ManeuverType::UTurn;
        CHECK(link.maneuverName() == "UTurn");
    }

    TEST_CASE("LaneGraph empty") {
        geo::LaneGraph graph;
        CHECK(graph.numNodes() == 0);
        CHECK(graph.numLinks() == 0);
        CHECK(graph.incomingNodes().empty());
        CHECK(graph.outgoingNodes().empty());
        CHECK(graph.findNode("nonexistent") == nullptr);
    }

    TEST_CASE("LaneGraph with nodes") {
        geo::LaneGraph graph;
        graph.junctionId = "j1";

        geo::LaneNode in1;
        in1.id = "roadA_lane+1_Incoming";
        in1.type = geo::LaneEndpointType::Incoming;
        graph.nodes.push_back(in1);

        geo::LaneNode out1;
        out1.id = "roadB_lane+1_Outgoing";
        out1.type = geo::LaneEndpointType::Outgoing;
        graph.nodes.push_back(out1);

        CHECK(graph.numNodes() == 2);
        CHECK(graph.incomingNodes().size() == 1);
        CHECK(graph.outgoingNodes().size() == 1);
        CHECK(graph.findNode("roadA_lane+1_Incoming") != nullptr);
        CHECK(graph.findNode("nonexistent") == nullptr);
    }

    TEST_CASE("LaneGraph with links") {
        geo::LaneGraph graph;

        geo::LaneNode in1;
        in1.id = "in1";
        in1.type = geo::LaneEndpointType::Incoming;
        graph.nodes.push_back(in1);

        geo::LaneNode out1;
        out1.id = "out1";
        out1.type = geo::LaneEndpointType::Outgoing;
        graph.nodes.push_back(out1);

        geo::LaneLink link;
        link.id = "link_0";
        link.fromLaneNodeId = "in1";
        link.toLaneNodeId = "out1";
        link.maneuver = geo::ManeuverType::Straight;
        graph.links.push_back(link);

        CHECK(graph.numLinks() == 1);
        CHECK(graph.linksFrom("in1").size() == 1);
        CHECK(graph.linksTo("out1").size() == 1);
        CHECK(graph.linksFrom("out1").empty());
        CHECK(graph.linksTo("in1").empty());
    }

    TEST_CASE("LaneGraphBuilder: empty input") {
        geo::RoadNode junction;
        junction.type = geo::RoadNodeType::Junction;
        geo::RoadGraph graph;
        std::map<std::string, geo::LaneNetwork> laneNets;

        auto result = geo::LaneGraphBuilder::build(junction, graph, laneNets);
        CHECK(result.numNodes() == 0);
        CHECK(result.numLinks() == 0);
    }

    TEST_CASE("LaneGraphBuilder: non-junction returns empty") {
        geo::RoadNode node;
        node.type = geo::RoadNodeType::EndPoint;
        geo::RoadGraph graph;
        std::map<std::string, geo::LaneNetwork> laneNets;

        auto result = geo::LaneGraphBuilder::build(node, graph, laneNets);
        CHECK(result.numNodes() == 0);
    }
}

#endif // DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
