#pragma once

// ============================================================
// RailNetworkDefinitionExporter — Train Studio XML export
// ============================================================
//
// Produces the three WorldBuilder-compatible railway definitions
// described by the reconstruction specification:
//   base_network.xml  - track geometry and connectivity
//   helper.xml        - materials, texture references, metadata
//   track_names.xml   - track names and profile groups
//
// The exporter deliberately uses Qt's XML writer so the native Qt
// application has no QGIS or JavaScript dependency.

#include "RailImportPipeline.hpp"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSet>
#include <QStringList>
#include <QXmlStreamWriter>

#include <algorithm>
#include <cmath>

namespace osm {

struct RailXmlExportResult {
    bool success = false;
    QString errorMessage;
    QString outputDirectory;
    QString baseNetworkPath;
    QString helperPath;
    QString trackNamesPath;
    int segmentCount = 0;
    int connectionCount = 0;
};

class RailNetworkDefinitionExporter {
public:
    static RailXmlExportResult exportProject(const QString& outputDirectory,
                                             const RailImportResult& import,
                                             const QString& texturePath)
    {
        RailXmlExportResult result;
        result.outputDirectory = QDir::cleanPath(outputDirectory);
        result.baseNetworkPath = QDir(result.outputDirectory).filePath("base_network.xml");
        result.helperPath = QDir(result.outputDirectory).filePath("helper.xml");
        result.trackNamesPath = QDir(result.outputDirectory).filePath("track_names.xml");

        if (!import.success) {
            result.errorMessage = import.errorMessage.isEmpty()
                ? QStringLiteral("Rail import result is not successful")
                : import.errorMessage;
            return result;
        }
        if (result.outputDirectory.isEmpty() || !QDir().mkpath(result.outputDirectory)) {
            result.errorMessage = QStringLiteral("Could not create XML output directory");
            return result;
        }

        const QString normalizedTexture = QFileInfo(texturePath).exists()
            ? QFileInfo(texturePath).absoluteFilePath()
            : texturePath;

        if (!writeBaseNetwork(result.baseNetworkPath, import, normalizedTexture,
                              result.segmentCount, result.connectionCount,
                              result.errorMessage)) {
            return result;
        }
        if (!writeHelper(result.helperPath, import, normalizedTexture, result.errorMessage)) {
            return result;
        }
        if (!writeTrackNames(result.trackNamesPath, import, result.errorMessage)) {
            return result;
        }

        result.success = true;
        return result;
    }

private:
    static bool openFile(QFile& file, QString& error)
    {
        if (file.open(QIODevice::WriteOnly | QIODevice::Text)) return true;
        error = QStringLiteral("Could not write %1: %2")
            .arg(file.fileName(), file.errorString());
        return false;
    }

    static QString relativeTexturePath(const QString& texturePath,
                                       const QString& outputPath)
    {
        if (texturePath.isEmpty()) return {};
        const QString relative = QDir(QFileInfo(outputPath).absolutePath())
            .relativeFilePath(QFileInfo(texturePath).absoluteFilePath());
        return relative.isEmpty() ? QFileInfo(texturePath).fileName() : relative;
    }

    static void writeHeader(QXmlStreamWriter& xml)
    {
        xml.writeStartDocument();
        xml.writeComment(QStringLiteral("Generated by OpenGeoStudio Train Studio"));
    }

    static QString wayType(const RailImportResult& import, const QString& roadId)
    {
        const auto* metadata = RoadNetworkBuilder::getMetadata(roadId.toStdString());
        if (metadata && !metadata->highwayType.isEmpty()) return metadata->highwayType;
        return QStringLiteral("rail");
    }

    static QString wayName(const geo::RoadV2& road)
    {
        return QString::fromStdString(road.name).isEmpty()
            ? QStringLiteral("Track")
            : QString::fromStdString(road.name);
    }

    static void writeTrackGeometry(QXmlStreamWriter& xml, const geo::RoadV2& road)
    {
        xml.writeStartElement(QStringLiteral("geometry"));
        xml.writeAttribute(QStringLiteral("pointCount"),
                           QString::number(road.numSegments() + 1));

        for (int i = 0; i < road.numSegments(); ++i) {
            const auto& segment = road.segment(i);
            const auto start = segment.startPoint();
            xml.writeStartElement(QStringLiteral("point"));
            xml.writeAttribute(QStringLiteral("x"), QString::number(start.x, 'f', 6));
            xml.writeAttribute(QStringLiteral("y"), QString::number(start.y, 'f', 6));
            xml.writeAttribute(QStringLiteral("z"), QStringLiteral("0.000000"));
            xml.writeAttribute(QStringLiteral("s"), QString::number(i));
            xml.writeEndElement();
        }

        if (road.numSegments() > 0) {
            const auto end = road.segment(road.numSegments() - 1).endPoint();
            xml.writeStartElement(QStringLiteral("point"));
            xml.writeAttribute(QStringLiteral("x"), QString::number(end.x, 'f', 6));
            xml.writeAttribute(QStringLiteral("y"), QString::number(end.y, 'f', 6));
            xml.writeAttribute(QStringLiteral("z"), QStringLiteral("0.000000"));
            xml.writeAttribute(QStringLiteral("s"), QString::number(road.numSegments()));
            xml.writeEndElement();
        }
        xml.writeEndElement();
    }

    static bool writeBaseNetwork(const QString& path,
                                 const RailImportResult& import,
                                 const QString& texturePath,
                                 int& segmentCount,
                                 int& connectionCount,
                                 QString& error)
    {
        QFile file(path);
        if (!openFile(file, error)) return false;

        QXmlStreamWriter xml(&file);
        xml.setAutoFormatting(true);
        writeHeader(xml);
        xml.writeStartElement(QStringLiteral("base_network"));
        xml.writeDefaultNamespace(QStringLiteral("http://www.sydac.com.au/WorldDefinition/1.0/"));
        xml.writeAttribute(QStringLiteral("version"), QStringLiteral("1.0"));
        xml.writeAttribute(QStringLiteral("coordinateSystem"), QStringLiteral("local-meters"));
        xml.writeAttribute(QStringLiteral("gauge"), QStringLiteral("1.435"));

        xml.writeStartElement(QStringLiteral("materials"));
        xml.writeStartElement(QStringLiteral("material"));
        xml.writeAttribute(QStringLiteral("id"), QStringLiteral("trackbed"));
        xml.writeAttribute(QStringLiteral("type"), QStringLiteral("rail-ballast"));
        xml.writeAttribute(QStringLiteral("albedo"), relativeTexturePath(texturePath, path));
        xml.writeEndElement();
        xml.writeEndElement();

        xml.writeStartElement(QStringLiteral("segments"));
        for (const auto& road : import.network.roads) {
            const QString id = QString::fromStdString(road.id);
            const double length = road.totalLength();
            if (id.isEmpty() || road.numSegments() == 0 || length <= 0.0) continue;

            xml.writeStartElement(QStringLiteral("segment"));
            xml.writeAttribute(QStringLiteral("id"), id);
            xml.writeAttribute(QStringLiteral("name"), wayName(road));
            xml.writeAttribute(QStringLiteral("type"), QStringLiteral("STRAIGHT"));
            xml.writeAttribute(QStringLiteral("railwayType"), wayType(import, id));
            xml.writeAttribute(QStringLiteral("length"), QString::number(length, 'f', 6));
            xml.writeAttribute(QStringLiteral("material"), QStringLiteral("trackbed"));
            xml.writeAttribute(QStringLiteral("gauge"), QStringLiteral("1.435"));
            xml.writeAttribute(QStringLiteral("mainLine"), QStringLiteral("true"));
            writeTrackGeometry(xml, road);
            xml.writeEndElement();
            ++segmentCount;
        }
        xml.writeEndElement();

        xml.writeStartElement(QStringLiteral("connections"));
        QSet<QString> emitted;
        for (const auto& [nodeId, node] : import.network.nodes) {
            QStringList ids;
            for (const auto& id : node.roadIds) {
                if (!ids.contains(id)) ids.append(id);
            }
            std::sort(ids.begin(), ids.end());
            for (int i = 0; i < ids.size(); ++i) {
                for (int j = i + 1; j < ids.size(); ++j) {
                    const QString key = ids[i] + QLatin1Char('|') + ids[j]
                        + QLatin1Char('|') + QString::number(nodeId);
                    if (emitted.contains(key)) continue;
                    emitted.insert(key);
                    xml.writeStartElement(QStringLiteral("connection"));
                    xml.writeAttribute(QStringLiteral("id"),
                                       QStringLiteral("connection_%1").arg(connectionCount));
                    xml.writeAttribute(QStringLiteral("nodeId"), QString::number(nodeId));
                    xml.writeAttribute(QStringLiteral("from"), ids[i]);
                    xml.writeAttribute(QStringLiteral("to"), ids[j]);
                    xml.writeAttribute(QStringLiteral("type"),
                                       ids.size() >= 3 ? QStringLiteral("switch")
                                                       : QStringLiteral("continuous"));
                    xml.writeEndElement();
                    ++connectionCount;
                }
            }
        }
        xml.writeEndElement();
        xml.writeEndElement();
        xml.writeEndDocument();
        file.close();
        return xml.hasError() ? (error = QStringLiteral("XML write failed: %1").arg(path), false) : true;
    }

    static bool writeHelper(const QString& path,
                            const RailImportResult& import,
                            const QString& texturePath,
                            QString& error)
    {
        QFile file(path);
        if (!openFile(file, error)) return false;
        QXmlStreamWriter xml(&file);
        xml.setAutoFormatting(true);
        writeHeader(xml);
        xml.writeStartElement(QStringLiteral("helper"));
        xml.writeDefaultNamespace(QStringLiteral("http://www.sydac.com.au/WorldDefinition/1.0/"));
        xml.writeStartElement(QStringLiteral("materials"));
        xml.writeStartElement(QStringLiteral("material"));
        xml.writeAttribute(QStringLiteral("id"), QStringLiteral("trackbed"));
        xml.writeAttribute(QStringLiteral("name"), QStringLiteral("Trackbed Ballast"));
        xml.writeAttribute(QStringLiteral("albedoTexture"), texturePath);
        xml.writeAttribute(QStringLiteral("textureFormat"), QStringLiteral("DDS"));
        xml.writeAttribute(QStringLiteral("uvTiling"), QStringLiteral("4.0,1.0"));
        xml.writeEndElement();
        xml.writeEndElement();
        xml.writeStartElement(QStringLiteral("import"));
        xml.writeAttribute(QStringLiteral("osmNodes"), QString::number(import.stats.osmNodes));
        xml.writeAttribute(QStringLiteral("osmWays"), QString::number(import.stats.osmWays));
        xml.writeAttribute(QStringLiteral("tracks"), QString::number(import.stats.tracksCreated));
        xml.writeAttribute(QStringLiteral("coordinateReferenceLat"),
                           QString::number(import.converter.refLat, 'f', 8));
        xml.writeAttribute(QStringLiteral("coordinateReferenceLon"),
                           QString::number(import.converter.refLon, 'f', 8));
        xml.writeEndElement();
        xml.writeEndElement();
        xml.writeEndDocument();
        file.close();
        return !xml.hasError();
    }

    static bool writeTrackNames(const QString& path,
                                const RailImportResult& import,
                                QString& error)
    {
        QFile file(path);
        if (!openFile(file, error)) return false;
        QXmlStreamWriter xml(&file);
        xml.setAutoFormatting(true);
        writeHeader(xml);
        xml.writeStartElement(QStringLiteral("track_names"));
        xml.writeDefaultNamespace(QStringLiteral("http://www.sydac.com.au/WorldDefinition/1.0/"));
        xml.writeStartElement(QStringLiteral("profiles"));
        xml.writeStartElement(QStringLiteral("profile"));
        xml.writeAttribute(QStringLiteral("id"), QStringLiteral("mainline"));
        xml.writeAttribute(QStringLiteral("name"), QStringLiteral("Main Line"));
        xml.writeAttribute(QStringLiteral("gauge"), QStringLiteral("1.435"));
        xml.writeAttribute(QStringLiteral("material"), QStringLiteral("trackbed"));
        xml.writeEndElement();
        xml.writeEndElement();
        xml.writeStartElement(QStringLiteral("tracks"));
        for (const auto& road : import.network.roads) {
            if (road.numSegments() == 0 || road.totalLength() <= 0.0) continue;
            xml.writeStartElement(QStringLiteral("track"));
            xml.writeAttribute(QStringLiteral("name"), wayName(road));
            xml.writeAttribute(QStringLiteral("segmentId"), QString::fromStdString(road.id));
            xml.writeAttribute(QStringLiteral("profile"), QStringLiteral("mainline"));
            xml.writeEndElement();
        }
        xml.writeEndElement();
        xml.writeEndElement();
        xml.writeEndDocument();
        file.close();
        return !xml.hasError();
    }
};

} // namespace osm
